---

- name: 'Configura NodeJs'
  hosts: managed
  connection: ssh
  gather_facts: false
  connection: network_cli

  tasks:
    - name: 'Certificar que o Git está instalado'
      apt:
        name: git
        state: present
        update_cache: yes
    
    - name: 'Clonar repositório'
      git:
        repo: 'https://github.com/Amoneleais/REST-Gestao-II'
        dest: '/home/vagrant/gc2'
        version: 'main'
        force: yes
    
    - name: 'Instalar NodeJs'
      shell: |
        curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash - && sudo apt-get install -y nodejs
    
    - name: 'Instalar dependências da aplicação'
      npm:
        path: '/home/vagrant/gc2'
        state: present
