---

- name: 'Configura NodeJs'
  hosts: gerenciado
  connection: ssh
  gather_facts: false
  connection: network_cli

  tasks:
    - name: 'Certificar que o Git está instalado'
      apt:
        name: git
        state: present
        update_cache: yes
    
    - name: 'Clonar repositório'
      git:
        repo: 'https://github.com/Amoneleais/REST-Gestao-II'
        dest: '/home/vagrant/gc2'
        version: 'main'
        force: yes
    
    - name: 'Instalar NodeJs'
      apt:
        name:
          - nodejs
          - npm
        state: present
    
    - name: 'Instalar dependências da aplicação'
      npm:
        path: '/home/vagrant/gc2'