name: CI for Commits

on:
  push:
    branches:
      - main
      - dev

jobs:
  ci-commit:
    name: CI for Commits
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'dev'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install All Dependencies
        run: npm install --save-dev sucrase
        run: npm install

      - name: Run Tests
        run: npm run test